### ISSUE TITLE
questions about the parameter settings

### ISSUE THREAD

**Issue by cjlin1** [yu54ku/xml-cnn#1]
I noticed that you have
  d_max_pool_p: [125, 128, 128]
  filter_sizes: [2, 4, 8]
  stride: [2, 1, 1]
May I ask why the first stride is 2?

Also how did you decide values shown in params.yml? The authors of
xml-CNN mentioned
  filter_channels: 128
  filter_sizes: [2, 4, 8]
  hidden_dims: 512
but how about others?

Thanks

**Comment by yu54ku** [comment]
Hello! Thank you for your issue.

I'll answer the question you asked.
The "stride size" used in this program was determined by parameter search.
To be precise, I'd parameter search for all parameters not shown in Liu et al.

Conversely, the parameters given in their paper are used as is.
In parameter search, these parameters were also fixed.

Note that these parameters were used in my environment.
I recommend that you perform parameter search again when you use this program.

However, you'll need to rewrite this program to select the parameters to explore.

Thanks!

**Comment by cjlin1** [comment]
Thanks. It seems you didn't answer my first question:

I noticed that you have
d_max_pool_p: [125, 128, 128]
filter_sizes: [2, 4, 8]
stride: [2, 1, 1]

Why when d_max_pool_p = 125 and filter_sizes = 2, you set stride = 2?

Thanks

**Comment by yu54ku** [comment]
Hello! Thank you for your issue.

I'll answer the question you asked.
As in the first answer, the parameters for stride are determined by parameter search.
So I don't know why I chose that value.
However, It's reasonable to assume that this value is appropriate.

Or, Do you think there is a problem with stride "2"? 

Thanks.

**Comment by cjlin1** [comment]
I see. I wrongly thought that stride was used in dynamic max pooling.

             pool_n = nn.MaxPool1d(pool_k_size, stride=pool_k_size)

Now I see that this "2" isn't related to the stride for dynamic
max pooling. So no problem. Thanks

**Comment by yu54ku** [comment]
I get it.

It seems that my explanation about stride was insufficient.
I'm sorry.

Have a nice research!
