### ISSUE TITLE
slightly worse p@1 than results in xml-cnn paper

### ISSUE THREAD

**Issue by cjlin1** [yu54ku/xml-cnn#3]
My two runs of the code showed

-------------- Best Epoch: 16 (p@1: 0.95296472311019897461) -------------

-------------- Best Epoch: 14 (p@1: 0.95154267549514770508) -------------

This p@1 result is slightly worse than the 96.86 presented
in the xml-cnn paper. Do you think the reason is because
of the slightly different tokenization?
Indeed I think as yours used more tokens, more information is used
and results should be as good?

Thanks

**Comment by yu54ku** [comment]
Hello! Thank you for your issue.

I'll answer the question you asked.
I think so too.
I think that tokenization affects the accuracy.

However, I'm not the author of "XML-CNN" paper, so I can't say for sure about the results in the paper.
Therefore, there is no guarantee that the datasets, models, and hyper parameters in this program are exactly the same as in the paper.

Thanks.

**Comment by cjlin1** [comment]
Thanks. Maybe another way to confirm this is by trying more sets. I plan 
to do that but would like to ask if you have done that before? (e.g., 
trying other sets such as EUR-Lex, Wiki-30K etc. used in the paper)? 
Thanks

**Comment by yu54ku** [comment]
I haven't tried any other datasets with this program.
Therefore, we don't know the results regarding them.

We also have a problem with Precision@k.
The method of calculating Precision@k has been shown in various ways in various papers and various programs.
Therefore, it's unlikely that we'll ever know which Precision@k was used by Liu et al.
In other words, it would be impossible for us to obtain exactly the same results as Liu et al.
